name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for possible build tools)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run path conversion script (absolute to relative)
        run: |
          bash convert_absolute_to_relative.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          publish_branch: gh-pages

      - name: Restore absolute paths for main branch
        if: always()
        run: |
          git checkout main
          bash convert_relative_to_absolute.sh
