name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Workflow per deploy automatico su GitHub Pages
      # The GitHub Action for deploying to GitHub Pages has been removed as the branch is no longer used.
